### ISSUE TITLE
Basic cmd tool for finding tickets that are not assigned to EPIC's

### ISSUE THREAD

**Issue by eolexe** [eolexe/zenhubext#1]
## Issue Workflow

- [x] New Issue is ready to be reviewed by repo owner or one of the core team members (@eolexe)
- [x] Issue clarified and all sections are fulfiled.
- [x] Issue estimated. (using zenhub)
- [x] Issue approval & prioritized

## Feature. User Story

As a zenhub user 
I want to be able to find all tickets that are not assigned to EPIC's and not EPIC itself
In order to  identify the tickets that might be missing EPIC
## Tasks
- [ ] get familiar with github api and find/chose golang package to work with service
- [ ] create basic cmd tool that fulfil userstory needs
