### ISSUE TITLE
Found a bug in note taking feature

### ISSUE THREAD

**Issue by eolexe** [eolexe/zenhubext#10]
## Issue Workflow

- [x] New Issue is ready to be reviewed by repo owner or one of the core team members (@eolexe)
- [ ] Issue clarified and all sections are fulfiled.
- [ ] Issue estimated. (using zenhub)
- [ ] Issue approval & prioritized

## Defect. Steps to Reproduce

As a user on senstone follow these steps to see the issues.

* try to sync device
* observe lights are not glowing 3 times but only 2

## Annotated Wireframes / Screenshots

none

## Tasks
?
