### ISSUE TITLE
Create Account

### ISSUE THREAD

**Issue by eolexe** [eolexe/zenhubext#15]
## Issue Workflow

- [x] New Issue is ready to be reviewed by repo owner or one of the core team members (@eolexe)
- [ ] Issue clarified and all sections are fulfiled.
- [ ] Issue estimated. (using zenhub)
- [ ] Issue approval & prioritized

## Feature. User Story
https://github.com/eolexe/zenhubext/wiki/ALL-user-stories#story-create-user-account

## Defect. Steps to Reproduce

As a (persona / User) on (browser) on (device) follow these steps to see the issues.

* 
* 
*
