### ISSUE TITLE
Sync github templates between multiple repos

### ISSUE THREAD

**Issue by eolexe** [eolexe/zenhubext#2]
## Issue Workflow

- [x] New Issue is ready to be reviewed by repo owner or one of the core team members (@eolexe)
- [ ] Issue clarified and all sections are fulfiled.
- [ ] Issue estimated. (using zenhub)
- [ ] Issue approval & prioritized

## Feature. User Story

As a user I want to be able to sync git hub issue templates between multiple repositories
## Tasks
- [ ] Ability to select a repository as a source
- [ ] Ability to copy source repo ISSUE_TEMPLATE to the target repos
