### ISSUE TITLE
Get a list of all tickets from multiple repos filtered by person

### ISSUE THREAD

**Issue by eolexe** [eolexe/zenhubext#3]
## Issue Workflow

- [x] New Issue is ready to be reviewed by repo owner or one of the core team members (@eolexe)
- [ ] Issue clarified and all sections are fulfiled.
- [ ] Issue estimated. (using zenhub)
- [ ] Issue approval & prioritized

## Feature. User Story

As a PM/TL, I want to get a list of all tickets that was submitted by a person in to the multiple github repos
## Tasks

TBD
