### ISSUE TITLE
User Managemnt

### ISSUE THREAD

**Issue by eolexe** [eolexe/zenhubext#5]
- [ ] as a user, I want to be able to register a Senstone account, to personalise my experience and protect my notes from unauthorised access

- [ ] as a user, I want to be able to delete my Senstone account, to make sure there’s none of my data left in Senstone system.

- [ ] as a user, I want to be able to log in to Senstone account, to access my notes and connect with my Senstone

- [ ] as a user, I want to be able to to log out of my Senstone account, to temporarily remove my Senstone data from my phone

- [ ] as a user, I want to be able to reset my password via email, to avoid losing access to my account in case I forget my password
