### ISSUE TITLE
Add backend API

### ISSUE THREAD

**Issue by eolexe** [eolexe/zenhubext#6]
## Issue Workflow

- [x] New Issue is ready to be reviewed by repo owner or one of the core team members (@eolexe)
- [ ] Issue clarified and all sections are fulfiled.
- [ ] Issue estimated. (using zenhub)
- [ ] Issue approval & prioritized

## Feature. User Story
As a user, I want to be able to register a Senstone account, to personalise my experience and protect my notes from unauthorised access

## Tasks
- [ ] Create API `POST /users`
- [ ] Document on apiary
