### ISSUE TITLE
Add iOS screen

### ISSUE THREAD

**Issue by eolexe** [eolexe/zenhubext#7]
## Issue Workflow

- [x] New Issue is ready to be reviewed by repo owner or one of the core team members (@eolexe)
- [ ] Issue clarified and all sections are fulfiled.
- [ ] Issue estimated. (using zenhub)
- [ ] Issue approval & prioritized

## Feature. User Story
as a user, I want to be able to register a Senstone account, to personalise my experience and protect my notes from unauthorised access

## Tasks
- [ ] Add screen for user login according to the wireframes provided
